### PR TITLE
In getUnixTime restrict the seconds field to Word32

### PR DESCRIPTION
**Pull request by jneira**
To fix the ouput of the function for some windows systems. See

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
@sighingnow Would you review this PR?

**Comment by sighingnow** [comment]
Good catch! There's definitely a problem here on Windows and that code hasn't been tested and needs to be fixed. Sorry that I didn't catch the real problem #54.

About the patch, I think we could `peek` a `UnixTime` value from `p_timeval` directly since the implementation of the `Storable` instance is correct. We could do something (better) like

```
getUnixTime :: IO UnixTime
getUnixTime = allocaBytes (#const sizeof(struct timeval)) $ \ p_timeval -> do
    throwErrnoIfMinus1_ "getClockTime" $ c_gettimeofday p_timeval nullPtr
    peek (castPtr p_timeval)
```

@jneira Would you mind to revise the patch?

**Comment by jneira** [comment]
@sighingnow Sure, i'll do it asap. I thought at first in reuse the `Storable` instance but finally i chose change the less possible code.

**Comment by jneira** [comment]
@sighingnow i've updated the pr with your suggestion
Thank you and @kazu-yamamoto for take care of the poor souls that use windows :wink:

**Comment by sighingnow** [comment]
The PR is LGTM now. @jneira Thanks for the work!

**Comment by kazu-yamamoto** [comment]
Merged. Thanks.

Ready for releasing?

**Comment by sighingnow** [comment]
Thanks for merging this pr. I think we could give #54 a try before the next release.

**Comment by kazu-yamamoto** [comment]
OK. Of course, I can wait.

**Pull request merged**
